/* cpu.c
 * Implements the CPU
 */

#include <stdio.h>
#include "cpu.h"
#include "memory.h"

void write_hi_byte(CPU* cpu, uint8_t byte, reg_pair_t reg)
{
    cpu->reg.hi_byte = byte;
}

void run(CPU* cpu)
{
    while(1)
    {
        switch(memory[PC])
        {
            case 0x00:  /* NOP */
            case 0x01:  /* LD BC, d16 */
            case 0x02:  /* NOP */
            case 0x03:  /* NOP */
            case 0x04:  /* NOP */
            case 0x05:  /* NOP */
            case 0x06:  /* NOP */
            case 0x07:  /* NOP */
            case 0x08:  /* NOP */
            case 0x09:  /* NOP */
            case 0x0A:  /* NOP */
            case 0x0B:  /* NOP */
            case 0x0C:  /* NOP */
            case 0x0D:  /* NOP */
            case 0x0E:  /* NOP */
            case 0x0F:  /* NOP */
            case 0x10:  /* NOP */
            case 0x11:  /* NOP */
            case 0x12:  /* NOP */
            case 0x13:  /* NOP */
            case 0x14:  /* NOP */
            case 0x15:  /* NOP */
            case 0x16:  /* NOP */
            case 0x17:  /* NOP */
            case 0x18:  /* NOP */
            case 0x19:  /* NOP */
            case 0x1A:  /* NOP */
            case 0x1B:  /* NOP */
            case 0x1C:  /* NOP */
            case 0x1D:  /* NOP */
            case 0x1E:  /* NOP */
            case 0x1F:  /* NOP */
            case 0x20:  /* NOP */
            case 0x21:  /* NOP */
            case 0x22:  /* NOP */
            case 0x23:  /* NOP */
            case 0x24:  /* NOP */
            case 0x25:  /* NOP */
            case 0x26:  /* NOP */
            case 0x27:  /* NOP */
            case 0x28:  /* NOP */
            case 0x29:  /* NOP */
            case 0x2A:  /* NOP */
            case 0x2B:  /* NOP */
            case 0x2C:  /* NOP */
            case 0x2D:  /* NOP */
            case 0x2E:  /* NOP */
            case 0x2F:  /* NOP */
            case 0x30:  /* NOP */
            case 0x31:  /* NOP */
            case 0x32:  /* NOP */
            case 0x33:  /* NOP */
            case 0x34:  /* NOP */
            case 0x35:  /* NOP */
            case 0x36:  /* NOP */
            case 0x37:  /* NOP */
            case 0x38:  /* NOP */
            case 0x39:  /* NOP */
            case 0x3A:  /* NOP */
            case 0x3B:  /* NOP */
            case 0x3C:  /* NOP */
            case 0x3D:  /* NOP */
            case 0x3E:  /* NOP */
            case 0x3F:  /* NOP */
            case 0x40:  /* NOP */
            case 0x41:  /* NOP */
            case 0x42:  /* NOP */
            case 0x43:  /* NOP */
            case 0x44:  /* NOP */
            case 0x45:  /* NOP */
            case 0x46:  /* NOP */
            case 0x47:  /* NOP */
            case 0x48:  /* NOP */
            case 0x49:  /* NOP */
            case 0x4A:  /* NOP */
            case 0x4B:  /* NOP */
            case 0x4C:  /* NOP */
            case 0x4D:  /* NOP */
            case 0x4E:  /* NOP */
            case 0x4F:  /* NOP */
            case 0x50:  /* NOP */
            case 0x51:  /* NOP */
            case 0x52:  /* NOP */
            case 0x53:  /* NOP */
            case 0x54:  /* NOP */
            case 0x55:  /* NOP */
            case 0x56:  /* NOP */
            case 0x57:  /* NOP */
            case 0x58:  /* NOP */
            case 0x59:  /* NOP */
            case 0x5A:  /* NOP */
            case 0x5B:  /* NOP */
            case 0x5C:  /* NOP */
            case 0x5D:  /* NOP */
            case 0x5E:  /* NOP */
            case 0x5F:  /* NOP */
            case 0x60:  /* NOP */
            case 0x61:  /* NOP */
            case 0x62:  /* NOP */
            case 0x63:  /* NOP */
            case 0x64:  /* NOP */
            case 0x65:  /* NOP */
            case 0x66:  /* NOP */
            case 0x67:  /* NOP */
            case 0x68:  /* NOP */
            case 0x69:  /* NOP */
            case 0x6A:  /* NOP */
            case 0x6B:  /* NOP */
            case 0x6C:  /* NOP */
            case 0x6D:  /* NOP */
            case 0x6E:  /* NOP */
            case 0x6F:  /* NOP */
            case 0x70:  /* NOP */
            case 0x71:  /* NOP */
            case 0x72:  /* NOP */
            case 0x73:  /* NOP */
            case 0x74:  /* NOP */
            case 0x75:  /* NOP */
            case 0x76:  /* NOP */
            case 0x77:  /* NOP */
            case 0x78:  /* NOP */
            case 0x79:  /* NOP */
            case 0x7A:  /* NOP */
            case 0x7B:  /* NOP */
            case 0x7C:  /* NOP */
            case 0x7D:  /* NOP */
            case 0x7E:  /* NOP */
            case 0x7F:  /* NOP */
            case 0x80:  /* NOP */
            case 0x81:  /* NOP */
            case 0x82:  /* NOP */
            case 0x83:  /* NOP */
            case 0x84:  /* NOP */
            case 0x85:  /* NOP */
            case 0x86:  /* NOP */
            case 0x87:  /* NOP */
            case 0x88:  /* NOP */
            case 0x89:  /* NOP */
            case 0x8A:  /* NOP */
            case 0x8B:  /* NOP */
            case 0x8C:  /* NOP */
            case 0x8D:  /* NOP */
            case 0x8E:  /* NOP */
            case 0x8F:  /* NOP */
            case 0x90:  /* NOP */
            case 0x91:  /* NOP */
            case 0x92:  /* NOP */
            case 0x93:  /* NOP */
            case 0x94:  /* NOP */
            case 0x95:  /* NOP */
            case 0x96:  /* NOP */
            case 0x97:  /* NOP */
            case 0x98:  /* NOP */
            case 0x99:  /* NOP */
            case 0x9A:  /* NOP */
            case 0x9B:  /* NOP */
            case 0x9C:  /* NOP */
            case 0x9D:  /* NOP */
            case 0x9E:  /* NOP */
            case 0x9F:  /* NOP */
            case 0xA0:  /* NOP */
            case 0xA1:  /* NOP */
            case 0xA2:  /* NOP */
            case 0xA3:  /* NOP */
            case 0xA4:  /* NOP */
            case 0xA5:  /* NOP */
            case 0xA6:  /* NOP */
            case 0xA7:  /* NOP */
            case 0xA8:  /* NOP */
            case 0xA9:  /* NOP */
            case 0xAA:  /* NOP */
            case 0xAB:  /* NOP */
            case 0xAC:  /* NOP */
            case 0xAD:  /* NOP */
            case 0xAE:  /* NOP */
            case 0xAF:  /* NOP */
            case 0xB0:  /* NOP */
            case 0xB1:  /* NOP */
            case 0xB2:  /* NOP */
            case 0xB3:  /* NOP */
            case 0xB4:  /* NOP */
            case 0xB5:  /* NOP */
            case 0xB6:  /* NOP */
            case 0xB7:  /* NOP */
            case 0xB8:  /* NOP */
            case 0xB9:  /* NOP */
            case 0xBA:  /* NOP */
            case 0xBB:  /* NOP */
            case 0xBC:  /* NOP */
            case 0xBD:  /* NOP */
            case 0xBE:  /* NOP */
            case 0xBF:  /* NOP */
            case 0xC0:  /* NOP */
            case 0xC1:  /* NOP */
            case 0xC2:  /* NOP */
            case 0xC3:  /* NOP */
            case 0xC4:  /* NOP */
            case 0xC5:  /* NOP */
            case 0xC6:  /* NOP */
            case 0xC7:  /* NOP */
            case 0xC8:  /* NOP */
            case 0xC9:  /* NOP */
            case 0xCA:  /* NOP */
            case 0xCB:  /* NOP */
            case 0xCC:  /* NOP */
            case 0xCD:  /* NOP */
            case 0xCE:  /* NOP */
            case 0xCF:  /* NOP */
            case 0xD0:  /* NOP */
            case 0xD1:  /* NOP */
            case 0xD2:  /* NOP */
            case 0xD3:  /* NOP */
            case 0xD4:  /* NOP */
            case 0xD5:  /* NOP */
            case 0xD6:  /* NOP */
            case 0xD7:  /* NOP */
            case 0xD8:  /* NOP */
            case 0xD9:  /* NOP */
            case 0xDA:  /* NOP */
            case 0xDB:  /* NOP */
            case 0xDC:  /* NOP */
            case 0xDD:  /* NOP */
            case 0xDE:  /* NOP */
            case 0xDF:  /* NOP */
            case 0xE0:  /* NOP */
            case 0xE1:  /* NOP */
            case 0xE2:  /* NOP */
            case 0xE3:  /* NOP */
            case 0xE4:  /* NOP */
            case 0xE5:  /* NOP */
            case 0xE6:  /* NOP */
            case 0xE7:  /* NOP */
            case 0xE8:  /* NOP */
            case 0xE9:  /* NOP */
            case 0xEA:  /* NOP */
            case 0xEB:  /* NOP */
            case 0xEC:  /* NOP */
            case 0xED:  /* NOP */
            case 0xEE:  /* NOP */
            case 0xEF:  /* NOP */
            case 0xF0:  /* NOP */
            case 0xF1:  /* NOP */
            case 0xF2:  /* NOP */
            case 0xF3:  /* NOP */
            case 0xF4:  /* NOP */
            case 0xF5:  /* NOP */
            case 0xF6:  /* NOP */
            case 0xF7:  /* NOP */
            case 0xF8:  /* NOP */
            case 0xF9:  /* NOP */
            case 0xFA:  /* NOP */
            case 0xFB:  /* NOP */
            case 0xFC:  /* NOP */
            case 0xFD:  /* NOP */
            case 0xFE:  /* NOP */
            case 0xFF:  /* NOP */
            default:
                printf("Unrecognized opcode!");
                break;
        }
    }
}
